[2025-02-23T19:25:49.098+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T19:25:49.113+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AlphaVantage_Stock_Price_Prediction_Analysis.train_model scheduled__2025-02-21T21:15:00+00:00 [queued]>
[2025-02-23T19:25:49.117+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AlphaVantage_Stock_Price_Prediction_Analysis.train_model scheduled__2025-02-21T21:15:00+00:00 [queued]>
[2025-02-23T19:25:49.117+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-02-23T19:25:49.127+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): train_model> on 2025-02-21 21:15:00+00:00
[2025-02-23T19:25:49.140+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=10496) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T19:25:49.139+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'AlphaVantage_Stock_Price_Prediction_Analysis', 'train_model', 'scheduled__2025-02-21T21:15:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/api.py', '--cfg-path', '/tmp/tmpg3eylej4']
[2025-02-23T19:25:49.143+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask train_model
[2025-02-23T19:25:49.142+0000] {standard_task_runner.py:72} INFO - Started process 10499 to run task
[2025-02-23T19:25:49.198+0000] {task_command.py:467} INFO - Running <TaskInstance: AlphaVantage_Stock_Price_Prediction_Analysis.train_model scheduled__2025-02-21T21:15:00+00:00 [running]> on host b90f03c6f926
[2025-02-23T19:25:49.250+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AlphaVantage_Stock_Price_Prediction_Analysis' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T21:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-21T21:15:00+00:00'
[2025-02-23T19:25:49.251+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-23T19:25:50.575+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-02-23T19:27:14.895+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-02-23T19:27:14.896+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-23T19:27:14.897+0000] {process_utils.py:132} INFO - Sending 15 to group 10499. PIDs of all processes in the group: [10499]
[2025-02-23T19:27:14.897+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 10499
[2025-02-23T19:27:14.899+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-23T19:27:14.934+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-23T19:27:14.955+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=10499, status='terminated', exitcode=0, started='19:25:48') (10499) terminated with exit code 0
