[2025-02-22T23:36:39.267+0000] {processor.py:186} INFO - Started process (PID=691) to work on /opt/airflow/dags/api.py
[2025-02-22T23:36:39.270+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:36:39.273+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:36:39.273+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:36:39.277+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:36:39.299+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.048 seconds
[2025-02-22T23:37:09.706+0000] {processor.py:186} INFO - Started process (PID=703) to work on /opt/airflow/dags/api.py
[2025-02-22T23:37:09.707+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:37:09.711+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:37:09.710+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:37:09.719+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:37:09.735+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.041 seconds
[2025-02-22T23:37:40.036+0000] {processor.py:186} INFO - Started process (PID=714) to work on /opt/airflow/dags/api.py
[2025-02-22T23:37:40.037+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:37:40.042+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:37:40.041+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:37:40.046+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:37:40.061+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.033 seconds
[2025-02-22T23:38:10.367+0000] {processor.py:186} INFO - Started process (PID=725) to work on /opt/airflow/dags/api.py
[2025-02-22T23:38:10.369+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:38:10.371+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:38:10.371+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:38:10.374+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:38:10.388+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.031 seconds
[2025-02-22T23:38:11.376+0000] {processor.py:186} INFO - Started process (PID=730) to work on /opt/airflow/dags/api.py
[2025-02-22T23:38:11.377+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:38:11.378+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:38:11.378+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:38:11.395+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:38:11.394+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:38:11.395+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:38:11.404+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.031 seconds
[2025-02-22T23:38:18.505+0000] {processor.py:186} INFO - Started process (PID=735) to work on /opt/airflow/dags/api.py
[2025-02-22T23:38:18.506+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:38:18.508+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:38:18.507+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:38:18.530+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:38:18.528+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:38:18.530+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:38:18.536+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.037 seconds
[2025-02-22T23:38:48.873+0000] {processor.py:186} INFO - Started process (PID=746) to work on /opt/airflow/dags/api.py
[2025-02-22T23:38:48.875+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:38:48.880+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:38:48.879+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:38:48.903+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:38:48.902+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:38:48.904+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:38:48.914+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.053 seconds
[2025-02-22T23:39:19.280+0000] {processor.py:186} INFO - Started process (PID=757) to work on /opt/airflow/dags/api.py
[2025-02-22T23:39:19.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:39:19.285+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:39:19.285+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:39:19.313+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:39:19.310+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:39:19.314+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:39:19.321+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.051 seconds
[2025-02-22T23:39:49.670+0000] {processor.py:186} INFO - Started process (PID=768) to work on /opt/airflow/dags/api.py
[2025-02-22T23:39:49.671+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:39:49.673+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:39:49.673+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:39:49.688+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:39:49.687+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:39:49.688+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:39:49.694+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.036 seconds
[2025-02-22T23:40:20.039+0000] {processor.py:186} INFO - Started process (PID=779) to work on /opt/airflow/dags/api.py
[2025-02-22T23:40:20.040+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:40:20.044+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:40:20.044+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:40:20.083+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:40:20.081+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:40:20.083+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:40:20.091+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.059 seconds
[2025-02-22T23:40:50.460+0000] {processor.py:186} INFO - Started process (PID=790) to work on /opt/airflow/dags/api.py
[2025-02-22T23:40:50.462+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:40:50.465+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:40:50.465+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:40:50.498+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:40:50.496+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:40:50.498+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:40:50.505+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.057 seconds
[2025-02-22T23:41:20.803+0000] {processor.py:186} INFO - Started process (PID=800) to work on /opt/airflow/dags/api.py
[2025-02-22T23:41:20.805+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:41:20.808+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:41:20.808+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:41:20.829+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:41:20.827+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:41:20.829+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:41:20.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.038 seconds
[2025-02-22T23:41:51.206+0000] {processor.py:186} INFO - Started process (PID=811) to work on /opt/airflow/dags/api.py
[2025-02-22T23:41:51.208+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:41:51.212+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:41:51.210+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:41:51.251+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:41:51.246+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:41:51.252+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:41:51.266+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.068 seconds
[2025-02-22T23:42:21.699+0000] {processor.py:186} INFO - Started process (PID=822) to work on /opt/airflow/dags/api.py
[2025-02-22T23:42:21.700+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:42:21.704+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:42:21.704+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:42:21.755+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:42:21.753+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:42:21.755+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:42:21.762+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.071 seconds
[2025-02-22T23:42:52.098+0000] {processor.py:186} INFO - Started process (PID=833) to work on /opt/airflow/dags/api.py
[2025-02-22T23:42:52.100+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:42:52.103+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:42:52.102+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:42:52.133+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:42:52.131+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:42:52.133+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:42:52.140+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.047 seconds
[2025-02-22T23:43:22.515+0000] {processor.py:186} INFO - Started process (PID=844) to work on /opt/airflow/dags/api.py
[2025-02-22T23:43:22.516+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:43:22.520+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:43:22.519+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:43:22.550+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:43:22.549+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:43:22.551+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:43:22.560+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.056 seconds
[2025-02-22T23:43:52.915+0000] {processor.py:186} INFO - Started process (PID=855) to work on /opt/airflow/dags/api.py
[2025-02-22T23:43:52.917+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:43:52.920+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:43:52.920+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:43:52.956+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:43:52.954+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:43:52.957+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:43:52.964+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.057 seconds
[2025-02-22T23:44:23.267+0000] {processor.py:186} INFO - Started process (PID=866) to work on /opt/airflow/dags/api.py
[2025-02-22T23:44:23.268+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:44:23.272+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:44:23.272+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:44:23.297+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:44:23.295+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:44:23.298+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:44:23.305+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.046 seconds
[2025-02-22T23:44:53.652+0000] {processor.py:186} INFO - Started process (PID=877) to work on /opt/airflow/dags/api.py
[2025-02-22T23:44:53.653+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:44:53.656+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:44:53.655+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:44:53.674+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:44:53.673+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:44:53.675+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:44:53.682+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.035 seconds
[2025-02-22T23:45:24.042+0000] {processor.py:186} INFO - Started process (PID=888) to work on /opt/airflow/dags/api.py
[2025-02-22T23:45:24.043+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:45:24.046+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:45:24.045+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:45:24.066+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:45:24.065+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:45:24.067+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:45:24.075+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.039 seconds
[2025-02-22T23:45:54.419+0000] {processor.py:186} INFO - Started process (PID=899) to work on /opt/airflow/dags/api.py
[2025-02-22T23:45:54.420+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:45:54.422+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:45:54.422+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:45:54.441+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:45:54.439+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:45:54.442+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:45:54.449+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.036 seconds
[2025-02-22T23:46:24.828+0000] {processor.py:186} INFO - Started process (PID=910) to work on /opt/airflow/dags/api.py
[2025-02-22T23:46:24.829+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:46:24.831+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:46:24.831+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:46:24.850+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:46:24.849+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:46:24.851+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:46:24.858+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.037 seconds
[2025-02-22T23:46:55.167+0000] {processor.py:186} INFO - Started process (PID=921) to work on /opt/airflow/dags/api.py
[2025-02-22T23:46:55.168+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:46:55.170+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:46:55.170+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:46:55.189+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:46:55.187+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:46:55.189+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:46:55.196+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.036 seconds
[2025-02-22T23:47:25.626+0000] {processor.py:186} INFO - Started process (PID=932) to work on /opt/airflow/dags/api.py
[2025-02-22T23:47:25.627+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:47:25.631+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:47:25.631+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:47:25.671+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:47:25.669+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:47:25.671+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:47:25.680+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.067 seconds
[2025-02-22T23:47:55.942+0000] {processor.py:186} INFO - Started process (PID=942) to work on /opt/airflow/dags/api.py
[2025-02-22T23:47:55.943+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:47:55.945+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:47:55.945+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:47:55.963+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:47:55.961+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:47:55.963+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:47:55.970+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.034 seconds
[2025-02-22T23:48:26.330+0000] {processor.py:186} INFO - Started process (PID=953) to work on /opt/airflow/dags/api.py
[2025-02-22T23:48:26.331+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:48:26.335+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:48:26.335+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:48:26.364+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:48:26.362+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:48:26.364+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:48:26.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.052 seconds
[2025-02-22T23:48:56.729+0000] {processor.py:186} INFO - Started process (PID=964) to work on /opt/airflow/dags/api.py
[2025-02-22T23:48:56.730+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:48:56.732+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:48:56.732+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:48:56.750+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:48:56.749+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:48:56.751+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:48:56.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.035 seconds
[2025-02-22T23:49:27.105+0000] {processor.py:186} INFO - Started process (PID=975) to work on /opt/airflow/dags/api.py
[2025-02-22T23:49:27.107+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:49:27.111+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:49:27.111+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:49:27.125+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:49:27.124+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:49:27.126+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:49:27.131+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.035 seconds
[2025-02-22T23:49:57.444+0000] {processor.py:186} INFO - Started process (PID=986) to work on /opt/airflow/dags/api.py
[2025-02-22T23:49:57.446+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:49:57.450+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:49:57.450+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:49:57.489+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:49:57.486+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:49:57.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:49:57.503+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.066 seconds
[2025-02-22T23:50:27.831+0000] {processor.py:186} INFO - Started process (PID=997) to work on /opt/airflow/dags/api.py
[2025-02-22T23:50:27.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:50:27.859+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:50:27.858+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:50:27.895+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:50:27.893+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:50:27.895+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:50:27.903+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.082 seconds
[2025-02-22T23:50:58.272+0000] {processor.py:186} INFO - Started process (PID=1008) to work on /opt/airflow/dags/api.py
[2025-02-22T23:50:58.275+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:50:58.284+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:50:58.283+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:50:58.332+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:50:58.330+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:50:58.332+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:50:58.343+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.080 seconds
[2025-02-22T23:51:28.725+0000] {processor.py:186} INFO - Started process (PID=1025) to work on /opt/airflow/dags/api.py
[2025-02-22T23:51:28.726+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:51:28.733+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:51:28.733+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:51:28.775+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:51:28.773+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:51:28.776+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:51:28.783+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.071 seconds
[2025-02-22T23:51:59.133+0000] {processor.py:186} INFO - Started process (PID=1036) to work on /opt/airflow/dags/api.py
[2025-02-22T23:51:59.135+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:51:59.139+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:51:59.138+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:51:59.173+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:51:59.171+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:51:59.173+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:51:59.181+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.056 seconds
[2025-02-22T23:52:29.539+0000] {processor.py:186} INFO - Started process (PID=1047) to work on /opt/airflow/dags/api.py
[2025-02-22T23:52:29.542+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:52:29.546+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:52:29.546+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:52:29.572+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:52:29.571+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:52:29.573+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:52:29.580+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.052 seconds
[2025-02-22T23:52:59.933+0000] {processor.py:186} INFO - Started process (PID=1058) to work on /opt/airflow/dags/api.py
[2025-02-22T23:52:59.933+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:52:59.936+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:52:59.936+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:52:59.954+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:52:59.953+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:52:59.954+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:52:59.963+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.036 seconds
[2025-02-22T23:53:30.310+0000] {processor.py:186} INFO - Started process (PID=1069) to work on /opt/airflow/dags/api.py
[2025-02-22T23:53:30.311+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:53:30.313+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:53:30.313+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:53:30.333+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:53:30.332+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:53:30.334+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:53:30.343+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.039 seconds
[2025-02-22T23:54:00.751+0000] {processor.py:186} INFO - Started process (PID=1080) to work on /opt/airflow/dags/api.py
[2025-02-22T23:54:00.753+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:54:00.763+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:54:00.763+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:54:00.795+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:54:00.794+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:54:00.796+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:54:00.805+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.063 seconds
[2025-02-22T23:54:31.140+0000] {processor.py:186} INFO - Started process (PID=1091) to work on /opt/airflow/dags/api.py
[2025-02-22T23:54:31.141+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:54:31.146+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:54:31.145+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:54:31.177+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:54:31.173+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:54:31.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:54:31.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.058 seconds
[2025-02-22T23:55:01.505+0000] {processor.py:186} INFO - Started process (PID=1102) to work on /opt/airflow/dags/api.py
[2025-02-22T23:55:01.508+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:55:01.513+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:55:01.512+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:55:01.540+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:55:01.538+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:55:01.540+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:55:01.552+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.058 seconds
[2025-02-22T23:55:31.815+0000] {processor.py:186} INFO - Started process (PID=1113) to work on /opt/airflow/dags/api.py
[2025-02-22T23:55:31.816+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:55:31.818+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:55:31.818+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:55:31.834+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:55:31.833+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:55:31.835+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:55:31.845+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.036 seconds
[2025-02-22T23:56:02.147+0000] {processor.py:186} INFO - Started process (PID=1124) to work on /opt/airflow/dags/api.py
[2025-02-22T23:56:02.148+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:56:02.151+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:56:02.151+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:56:02.171+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:56:02.170+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:56:02.172+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:56:02.178+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.038 seconds
[2025-02-22T23:56:32.550+0000] {processor.py:186} INFO - Started process (PID=1135) to work on /opt/airflow/dags/api.py
[2025-02-22T23:56:32.552+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:56:32.556+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:56:32.556+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:56:32.586+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:56:32.584+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:56:32.586+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:56:32.597+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.057 seconds
[2025-02-22T23:57:02.953+0000] {processor.py:186} INFO - Started process (PID=1146) to work on /opt/airflow/dags/api.py
[2025-02-22T23:57:02.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:57:02.956+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:57:02.956+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:57:02.978+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:57:02.975+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:57:02.978+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:57:02.989+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.042 seconds
[2025-02-22T23:57:33.337+0000] {processor.py:186} INFO - Started process (PID=1158) to work on /opt/airflow/dags/api.py
[2025-02-22T23:57:33.339+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:57:33.342+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:57:33.342+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:57:33.364+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:57:33.362+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:57:33.364+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:57:33.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.042 seconds
[2025-02-22T23:58:03.712+0000] {processor.py:186} INFO - Started process (PID=1169) to work on /opt/airflow/dags/api.py
[2025-02-22T23:58:03.714+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:58:03.718+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:58:03.717+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:58:03.741+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:58:03.739+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:58:03.741+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:58:03.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.048 seconds
[2025-02-22T23:58:34.117+0000] {processor.py:186} INFO - Started process (PID=1180) to work on /opt/airflow/dags/api.py
[2025-02-22T23:58:34.119+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:58:34.123+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:58:34.123+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:58:34.151+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:58:34.149+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:58:34.152+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:58:34.160+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.053 seconds
[2025-02-22T23:59:04.500+0000] {processor.py:186} INFO - Started process (PID=1191) to work on /opt/airflow/dags/api.py
[2025-02-22T23:59:04.501+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:59:04.504+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:59:04.503+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:59:04.527+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:59:04.525+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:59:04.528+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:59:04.535+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.041 seconds
[2025-02-22T23:59:34.864+0000] {processor.py:186} INFO - Started process (PID=1202) to work on /opt/airflow/dags/api.py
[2025-02-22T23:59:34.866+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api.py for tasks to queue
[2025-02-22T23:59:34.869+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:59:34.869+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/api.py
[2025-02-22T23:59:34.890+0000] {logging_mixin.py:190} INFO - [2025-02-22T23:59:34.888+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api.py", line 142, in <module>
    api_key = Variable.get("alphavantage_apikey")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable alphavantage_apikey does not exist'
[2025-02-22T23:59:34.890+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api.py
[2025-02-22T23:59:34.901+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api.py took 0.044 seconds
